guardian/atoms-rendering

package.json
yarn.lock

Added the [emotion](https://emotion.sh/) css lib

Added emotion

---

package.json
src/ExplainerAtom.stories.tsx
src/ExplainerAtom.tsx
yarn.lock

`ExplainerAtom`
```typescript
type ExplainerAtomType = {
id: string;
title: string;
html: string;
};
```

ExplainerAtom

---

package.json
src/ExplainerAtom.tsx
src/index.ts
src/types.ts

Use `types.ts` to ensure applications that import our components have the right types

Refactor types

---

package.json
yarn.lock

- Move version to the top
- Bump src-foundations version
- Added react & react-dom to devDependencies
- Added emotion to peerDependencies

Refactor package.json

---

package.json
yarn.lock

If you see this
then do this
```
"jest": {
"testEnvironment": "jest-environment-jsdom-sixteen",
"moduleNameMapper": {
"^@guardian/src-foundations/(.*)$": "@guardian/src-foundations/$1/cjs"
}
}
```

Fix jest config

---

README.md

Update readme with yarn link instructions. #DevExperience

Update readme with yarn link instructions

---

package.json
src/QandaAtom.stories.tsx
src/QandaAtom.test.tsx
src/QandaAtom.tsx
src/types.ts
yarn.lock

Starting migration of Q and A atom.
Ophan tracking has now been added for EXPAND, LIKE and DISLIKE events.

Q and A Atom

---

src/GuideAtom.stories.tsx
src/GuideAtom.test.tsx
src/GuideAtom.tsx
src/ProfileAtom.stories.tsx
src/ProfileAtom.test.tsx
src/ProfileAtom.tsx
src/types.ts

Introduce GuideAtom and ProfileAtom together as they have same structure.

Introduce GuideAtom and ProfileAtom [wip]

---

package.json

Version bump to 1.8.0 to include Profile Atoms.

Version Bump 1.8.0 - Profile Atoms

---

package.json

Version bump which includes emotion escape error fix.

Version Bump 1.8.2

---

package.json

Bump Npm to 1.9.0 to include chart atoms

v1.9.0 NPM Bump

---

README.md

Minor update now that `main` is the default branch.

Update master -> main in publish section

---

src/types.ts

Redo of : https://github.com/guardian/atoms-rendering/pull/56

Types in alphabetical order

---

README.md

Update README with default branch instructions.

Update README with default branch instructions

---

package.json
src/ChartAtom.tsx

NPM bump to include some minor chart atom changes (and a linting fix!).

NPM bump 1.11.2

---

src/InteractiveAtom.tsx

Remove unused imports in InteractiveAtom (#cleaning)

Remove unused imports in InteractiveAtom

---

package.json

Update packages to v2
Make sure any repo updating updates dependencies to match

Update to v2

---

package.json

NPM Bump v2.0.1

---

package.json

NPM bump v2.0.2

---

.github/workflows/jest.yml
.github/workflows/lint.yml
.github/workflows/typescript.yml
package.json

Some more green ticks for warm fuzziness

More GitHub actions

---

src/AudioAtom.stories.tsx
src/AudioAtom.tsx

The little dot on the range slider was not picking up the pillar colour so this adds the styles to do that

Audio Colours

---

.github/workflows/chromatic.yml

Chromatic github action was broken, this fixes it.

Fix Chromatic

---

src/KnowledgeQuiz.tsx
src/PersonalityQuiz.tsx

Add padding to bottom of quiz
On DCR we need some space between the quiz and the footer content
Before:
After:

Quiz button padding

---

src/KnowledgeQuiz.tsx
src/PersonalityQuiz.tsx

Reverts guardian/atoms-rendering#163

Revert "Quiz button padding"

---

src/Picture.tsx
src/YoutubeAtom.stories.tsx
src/YoutubeAtom.test.tsx
src/YoutubeAtom.tsx
src/types.ts

Creates Picture component (copy from DCR https://github.com/guardian/dotcom-rendering/blob/main/src/web/components/Picture.tsx ) that pics the best image for rendering. Integrates this component in Youtube.
We plan on moving the Picture component from DCR to a seperate lib to be able to share the logic. In the meantime we can just copy over the code to match how the component works on DCR. 
Interact with youtube elemenets in Storybook (do they launch and hide the img?)
If there are changes to Picture component in DCR we would have to duplicate the changes here as well (until we move the logic to an external lib)

Picture component youtube

---

src/YoutubeAtom.stories.tsx
src/YoutubeAtom.test.tsx
src/YoutubeAtom.tsx

- Remove `videoMeta` and instead have each prop defined individually
- Change `overlayImage` to `overrideImage` to better match CAPI

Update youtube props

---

src/YoutubeAtom.tsx

Adds a cypress selector to the youtube overlay element

Cypress selector overlay

---

src/YoutubeAtom.stories.tsx
src/YoutubeAtom.tsx

Reverts guardian/atoms-rendering#180

Revert "Remove Origin URL when running development"

---

package.json
yarn.lock

Replaces our custom script used for publishing with the [np library](https://github.com/sindresorhus/np).
```bash
yarn release // Runs validation, builds and then opens an interactive UI to pubish changes
```

Added np lib for publishing

---

src/KnowledgeQuiz.tsx
src/PersonalityQuiz.tsx
src/YoutubeAtom.tsx

Add data attributes that will allow Telelporter for atoms to pick these up once Teleporter has gone through the Chrome validation.

Add Data Attributes for Teleporter

---

package.json
src/AudioAtom.tsx
src/KnowledgeQuiz.stories.tsx
src/PersonalityQuiz.stories.tsx
src/ProfileAtom.test.tsx
src/TimelineAtom.tsx
src/YoutubeAtom.stories.tsx
src/YoutubeAtom.test.tsx
src/YoutubeAtom.tsx
src/lib/unifyPageContent.test.tsx
src/lib/unifyPageContent.tsx

- Adds linting for `.tsx` files
- Fixes linting issues for `.tsx` files

Fix linting issues

---

.github/workflows/compress.yml

Adds Compress github action to check bundle size changes

Add Compress action

---

.github/dependabot.yml
package.json

- Add fix and check prettier actions to package.json
- ran `yarn prettier:fix` and pushed diff

Add Yarn actions for prettier

---

src/Answers.tsx

Update the designs of answer components

Quiz answer redesign

---

src/SharingIcons.tsx

Need to ignore global tag styles on social buttons

Ignore global a styles for link

---

.github/workflows/snyk.yml

Tests `devDependencies` in GH Action.

Test Snyk action with `devDependencies`

---

README.md

Update the readme to add a missing publishing process steps.

Better release instructions

---

src/YoutubeAtom.tsx

chore: Fix daya typo

---

src/YoutubeAtomPlayer.tsx

Moves the cleanup function that unregisters player listeners to an empty dependency `useEffect` to ensure the cleanup only runs on component unmount.
Currently the cleanup will [run on every trigger](https://maxrozen.com/demystifying-useeffect-cleanup-function) of the player initialisation `useEffect`.
This _shouldn't_ happen if all dependencies are stable but even so it is not the correct place for unregistration, which should only run on unmount.

YoutubeAtomPlayer - Fix listener unregister

---

.changeset/itchy-crabs-divide.md

docs(changeset): Test

---

.changeset/smooth-wasps-wink.md
src/YoutubeAtom.test.tsx

Fix `YoutubeAtom.test` TypeScript errors

Fix `YoutubeAtom.test` TypeScript errors

---

package.json
src/AudioAtom.tsx
src/PersonalityQuiz.tsx
src/YoutubeAtomPlayer.tsx
src/lib/ophan.ts
src/loadYouTubeIframeApi.ts

Implements eslint rule `prefer-optional-chain`

Prefer optional chain fixes

---

package.json
src/AudioAtom.tsx
src/GuideAtom.tsx
src/KnowledgeQuiz.tsx
src/PersonalityQuiz.tsx
src/ProfileAtom.tsx
src/QandaAtom.tsx
src/TimelineAtom.tsx
src/YoutubeAtom.tsx
src/YoutubeAtomOverlay.tsx
src/YoutubeAtomPlayer.tsx
src/lib/platformExampleScripts.tsx

Adds rule `@typescript-eslint/prefer-nullish-coalescing`

Fix nullish

---

package.json
src/YoutubeAtom.test.tsx
src/YoutubeAtomPlayer.tsx

Remove unused async
