package.json
tsconfig.json

Rename app > index and the build folder is called 'dist', not 'build'

Fix problem with exporting types

---

package.json

Replace `index.module.js` with `index.modern.js` to ensure we always have the latest and smallest build

Use modern build for module

---

src/ExplainerAtom.tsx

In DCR we override p tag spacing so we need to explicitly set it here.
We're also not seeing the `background` color come through so I'm moving it below `color` here.

Explainer styles

---

src/InteractiveAtom.tsx

This matches Frontend's styles for the interactive atom iframe
Removes the extra padding, because that was causing an issue with some interactive atoms

Remove iframe styles other than full width

---

package.json
yarn.lock

This is the basis for atoms-rendering version 1.5.0. This version now includes Q and A atoms

1.5.0 Version bump

---

package.json

Bump the atoms-rendering package to 1.7.0, which now includes timelines

Bump to 1.7.0 - Timeline Atoms

---

package.json

This bumps the version to include refactoring of the Q&A and Guide atoms.

Version bump to 1.8.1

---

.babelrc.js
package.json

This should remove emotion warnings in the console when running DCR locally. The errors were: 
`You have illegal escape sequence in your template literal, most likely inside content's property value. Because you write your CSS inside a JavaScript string you actually have to do double escaping, so for example "content: '\00d7';" should become "content: '\\00d7';". You can read more about this here:`
The sourceMap flag has been disabled in dev-mode in atoms-rendering.

Fix emotion console warnings

---

src/ChartAtom.stories.tsx
src/ChartAtom.test.tsx
src/ChartAtom.tsx
src/types.ts

Introduce ChartAtom. 
nb: The ChartAtom and the standard InteractiveAtom are identical in structure. Given by embeds.

Introduce ChartAtom [wip]

---

README.md

Add instruction to move the default branch from `master` to `main`.

Update README for moving default branch to main

---

README.md

Update the README to document the renaming of the Media atom to YoutubeAtom.

Document the renaming of the Media atom

---

tsconfig.json

Note: https://github.com/guardian/dotcom-rendering/pull/1900 is related and includes some necessary changes there to also fix const enum support. That PR depends on this one.
isolatedModules breaks some features, including const enums, that are used by @guardian/types. Let's enable it so that the transpiled code works for DCR and others.
`yarn link` and try using the `YoutubeAtom` in DCR for example, both on main and this branch. With main you will get an undefined error at runtime.

Fix const enums

---

src/expandableAtom/Container.tsx

Sets an explicit color style on the details element in the expandableAtom component instead of relying on outside page styles.
This would match the `ExplainerAtom` component https://github.com/guardian/atoms-rendering/blob/main/src/ExplainerAtom.tsx#L26
Without setting this color in the atom styles, we have some problems in dark mode on apps (screenshots below).
Users should see no difference.
apps-rendering dark mode.
| Before | After |
| --- | --- |
| <img src="https://user-images.githubusercontent.com/11618797/92597593-89922680-f29f-11ea-97ae-edcc3504bf8f.png" width="300" /> | <img src="https://user-images.githubusercontent.com/11618797/92597822-d4ac3980-f29f-11ea-8289-141aa5b0a56a.png" width="300" /> |

add explicit color style to detail element

---

.storybook/preview-head.html

This adds Guardian font urls to Storybook so that we don't have to rely on the fonts existing locally for them to appear in stories.
The motivation for this was when testing the Quiz Atom, where GuardianTextEgyptian was not rendering. The code is [copied from dotcom-rendering](https://github.com/guardian/dotcom-rendering/blob/main/.storybook/preview-head.html). 
Without this change:
With this change:
As an aside, is there a good way of keeping these fonts up to date?

Add fonts to storybook

---

src/ChartAtom.stories.tsx
src/ChartAtom.test.tsx
src/ChartAtom.tsx
src/types.ts

Simplify the props of ChartAtom. (The `url` is not needed).

Simplify the props of ChartAtom

---

src/AudioAtom.tsx

Make sure to put `audioEl.current.play()` within the onClick of a button.
Safari prevents HTML5 audio elements from playing unless they are triggered by user action (such as click).
We therefore need to make sure that `.play()` is called within that function and not from `useEffect`

Fix audio playing on safari

---

.storybook/preview-head.html
src/YoutubeAtom/YoutubeAtom.tsx
src/YoutubeAtom/YoutubeOverlay.tsx

Checks if `window` is defined before using that variable
When running this component on DCR, we would get a `window` is undefined. This is because when ServerSideRendering, window does not exist. Therefore we need to make a check that `window` exists before using it.

fix window undefined caused by SSR on Youtube block element

---

src/YoutubeAtom/YoutubeAtom.tsx

Origin string in URL should come from prop rather than being determined from atom
Make sure that youtube video is still playable for different URLs
if origin doesnt match URL, then the youtube video would be blocked from running

Youtube origin pass as prop

---

.storybook/main.js
package.json
src/Answers.tsx
src/AudioAtom.tsx
src/QuizAtom.test.tsx
src/QuizAtom.tsx
src/types.ts
yarn.lock

We should only serve audio with ads in it if the user has consented to this. This PR adds a check to see if the user has consented and, if they have, it reloads the AudioAtom using a new url, one which points to the Acast service to get ad enabled content.
Note. In the gifs below the 14m track is the one without ads, and the 17m track includes adverts.
Once this PR is merged, we need to
1. Release a new version of `@guardian/atoms-rendering`
2. Add the switch `acastEnabled` to DCR
3. Upgrade the version of `atoms-rendering` used in DCR and add the prop, `shouldUseAcast`, using CMP to check if the user has given consent or not

Acast Audio

---

.github/workflows/jest.yml
.github/workflows/lint.yml
.github/workflows/typescript.yml

Atoms-rendering is used by DCR (Node 10) and AR (Node 12), so it would be good to make sure it runs on both. These changes borrow heavily from [image-rendering](https://github.com/guardian/image-rendering/blob/cc9b89b96462a8df78d17bae69787597caaa6363/.github/workflows/node.js.yml).
**Note**: The lint warnings are present in `main`.
- Added a "matrix" to use both Node 10 and 12 for the "lint", "tsc" and "test" jobs

Use Both Node 12 And Node 10 In CI

---

src/InteractiveAtom.stories.tsx
src/InteractiveAtom.tsx

Prevents Chromatic taking snapshots of this component.
Because this custom animation is triggering false positives on every build, which is annoying.

Don't snapshot the Tube interactive

---

package.json
src/InteractiveAtom.tsx
src/lib/formatTime.ts

No more lint warning
Fixes a problem where eslint was warning about unused types that were in fact being used.
See: https://stackoverflow.com/questions/57802057/eslint-configuring-no-unused-vars-for-typescript
And also adds a missing return type for a function

Linting ❤️ 

---

.github/release-drafter.yml
.github/workflows/release-drafter.yml
README.md
package.json

This PR attempts to improve how we release code. It does this in two ways:
1. By adding the Github Action [Release Drafter](https://github.com/marketplace/actions/release-drafter) to aid in creating useful release documentation
2. By adding a `yarn release` script in `package.json` to automate the following steps:
- Building the package
- Bumping package version
- Adding a git tag
- Pushing the tag to `main`
- Publishing to Npm
- Launching a browser on the [releases page](https://github.com/oliverlloyd/publish-sandbox/releases) for the repo
The `release` script just runs `yarn version` under the hood and then that uses the `preversion` and `postversion` hooks to create a workflow
Eg.:
`yarn release` - Set version interactively
or
`yarn release -- patch` - 0.0.1
`yarn release -- minor` - …

Automate the release

---

src/VideoAtom.tsx
src/index.ts
src/types.ts

I missed added the correct exports for the `VideoAtom` on [my last PR](https://github.com/guardian/atoms-rendering/pull/109), adding them here.

Export video type

---

package.json
src/lib/unifyPageContent.tsx
yarn.lock

I was struggling with an error in Dotcom Rendering when trying to upgrade to Webpack 5:
```
ERROR in ./node_modules/@guardian/atoms-rendering/dist/index.modern.js 1:771-821
Module not found: Error: Package path ./compat/server is not exported from package /Users/gareth_trufitt/code/dotcom-rendering/node_modules/preact (see exports field in /Users/gareth_trufitt/code/dotcom-rendering/node_modules/preact/package.json)
```
The error came from the use of `import { renderToString } from 'react-dom/server';` in atoms-rendering, but I couldn't for the life of me get Dotcom Rendering to compile it properly, despite the use of it in DCR. I upgraded babel, webpack, preact, preact-render-to-string in both projects, messed around with webpack alias, ensured we were bundling etc but it just wouldn't …

Use preact render instead of render-to-string from react

---

README.md

Readme update: Remove obsolete [moving to main branch] instructions.

Remove obsolete instructions

---

package.json
src/YoutubeAtom.tsx
src/index.d.ts
tsconfig.json
yarn.lock

Use `youtube-player` to simplify interations with youttube embed iframe API. This removes the need to worry about if and when the player has been initialised, and allows use to easily add and remove event emitters to the player without having to implement our own event emiter logic.
Launch a video on storybook and check that it plays with and without overlay. You should see logs for each event we track on youtube but looking at the browser's console.
We now depend on the logic from `youtube-player`

Use youtube-player to simplify Atom

---

babel.config.js

Adds babel for optional chaining
should fix `yarn build`

Fix build by adding optional chaining babel

---

src/YoutubeAtom.test.tsx
src/YoutubeAtom.tsx

Adds some fixes to issues that appeared during DCR integration:
- convert`eventState` keys to string to help check
- add `await` to `player.getCurrentTime` and `player.getDuration`
- reduce interval from 1s to 0.5s (because we are using `async` `await` we risk skipping a second)
- use `let player` outside component, checking if has been defined before init
Potential unforseen race conditions

fix youtube atom

---

src/YoutubeAtom.test.tsx
src/YoutubeAtom.tsx
src/types.ts

- Use `useRef` to store player state
- Remove `onPlayerStateChangeAnalytics`  and instead move event dispatch logic all into useEffect.
- Simplify logic by moving boolean checks of it events dispatched to be within useEffect and not in or out of component state
On storybook, play through videos and in console check the events are all fired when they hit specific percentages (and that they are only fired once)
The useEffect is rerendered when eventEmitters changes. This means that events could be retriggered if that object changes. However it is likely that eventEmitters will change at most once, and will likely be done before the user plays the video. So there would be low to no impact.

Youtube progress tracker interval v2

---

src/AudioAtom.tsx

When toggling the play and pause buttons in Audio Atoms we would loose focus on the button because it would rerender.
To keep focus, we lift the button DOM element to only toggle the onClick and the child SVG, thus keeping the button DOM. Doing this allows us to keep focus on the button while toggling. 
Storybook use keyboard to launch audio atom

Fix accessiblity audio atom

---

src/Answers.tsx
src/KnowledgeQuiz.tsx

Lift selected answers state logic to parent to enable reset button to clear previous quiz selection

Reset knowledge quiz correctly

---

src/AudioAtom.stories.tsx
src/AudioAtom.test.tsx
src/AudioAtom.tsx
src/lib/pillarPalette.ts
src/types.ts

Replaces the `Pillar` value from @guardian/types with a locally defined one that is very similar but that includes `labs`
Because DCR needs labs supported. There is [an open PR](https://github.com/guardian/types/pull/42) to add labs to the /types repo but I want this to be a discussion and so by creating this workaround we remove the dependency and allow the PR time to be discussed if needed.

Pillar (with labs)

---

src/AudioAtom.stories.tsx
src/AudioAtom.test.tsx
src/AudioAtom.tsx
src/ProfileAtom.stories.tsx
src/ProfileAtom.test.tsx
src/TimelineAtom.tsx
src/expandableAtom/Body.tsx
src/expandableAtom/Container.tsx
src/expandableAtom/Footer.tsx
src/expandableAtom/Summary.tsx
src/fixtures/guideAtom.tsx
src/fixtures/qandaAtom.tsx
src/fixtures/timelineAtom.tsx
src/lib/pillarPalette.ts
src/types.ts

Replace the locally defined const enum Pillar with the import from @guardian/types
We were using a local const enum as a tempoary measure ahead of using the main type from /types

Use Pillar from @guardian/types

---

src/YoutubeAtom.stories.tsx
src/YoutubeAtom.test.tsx
src/YoutubeAtom.tsx

The Youtube overlay play buttons and duration now use decidePalette to choose the correct colour based on the pillar.

Replace Youtube overlay colours with decide palette

---

src/Answers.stories.tsx
src/Answers.tsx
src/KnowledgeQuiz.test.tsx
src/KnowledgeQuiz.tsx
src/PersonalityQuiz.test.tsx
src/PersonalityQuiz.tsx

We add a `submit` and `reset` button per question on the knowledge quiz
We use to instantly display correct and incorrect answers once an option was selected, but this was found to not work for keyboard users. Instead we went with the idea of having a submit button at the end of the quiz that would change the state of the quiz to display correct/incorrect answers based on selection.  
But that current implementation means that we display correct answers for questions we may not have answered, plus in terms of UX its not great as you would have to scroll back up and down to see what you got right and wrong.  
This is a compramise that keeps accessibility while maintaining some level of UX by not requiring up and down scrolls.
Check out the story, use keyboard and mouse to make sure you can …

Knowledge quiz submit per question

---

src/YoutubeAtom.stories.tsx
src/YoutubeAtom.tsx

Use `process.env.NODE_ENV` to detemin if running in Production. Make sure that origin is not set in development enviroments

Remove Origin URL when running development

---

tsconfig.json

Removes the [rootDir compiler option](https://www.typescriptlang.org/tsconfig#rootDir) so that Typescript decides which directory itself
This prevents the `/src` dir becoming part of the structure which causes discovery problems whem importing this lib elsewhere

Remove rootDir

---

src/PersonalityQuiz.test.tsx
src/PersonalityQuiz.tsx

`useState` on `PersonalityQuizAnswers` component and use `React. memo`  on `AnswersGroup` in order to be able to memoize rendering of Radio commponents.
Personality Quiz answer selection felt slow, this is because we had one global object that would contain key values of ever selected answer. Meaning updating that object would cause a re-render to every component. By moving the state lower, we can avoid re-renders, and instead through a `useEffect` we can update the global answer object.

Avoid unnessesary rerender personality quiz

---

src/YoutubeAtom.test.tsx
src/YoutubeAtom.tsx

This reverts the changes introduced to enable enhanced privacy mode for youtube atoms. This change would have had implications for advertising revenue for guardian videos hosted on youtube. 
The other youtube components on the site will continue to use the youtube-nocookie.com
This is consistent with the current implementation for details see:
https://github.com/guardian/frontend/pull/21747
There should be no drop in revenue when live blogs and video pages are served by DCR

Reverting  changes to use the youtube-nocookie.com in youtube atom

---

package.json

Remove `youtube-player` as a peer dependency and instead make it a dependency.
We do not use `youtube-player` in DCR. It makes sense for it to be bundled as part of atoms rendering

Make youtube-player as dependency

---

src/YoutubeAtom.tsx

Allow fullscreen support for youtube atoms videos

Youtube support fullscreen

---

src/expandableAtom/Body.tsx

Remove  `forceHeightAndWidth` as a className and instead put the styles within the image component

Remove forceHeightAndWidth as className

---

package.json
src/TimelineAtom.tsx
src/fixtures/timelineAtom.tsx
src/types.ts

Moves atoms-rendering to use the unixDate information passed through to fix a bug with Firefox not being able to parse dates in the format `month-year` e.g. "September 2011".
- https://github.com/guardian/frontend/pull/23504 (required to be live before this merges)
- https://github.com/guardian/dotcom-rendering/pull/2427
Run all PRs locally

Fix timeline events bug on firefox

---

.vscode/settings.json

Adds titlebar colouring to make it easier to distinguish between projects.
Colouring is based on this colour palette https://davidmathlogic.com/colorblind/#%23648FFF-%23785EF0-%23DC267F-%23FE6100-%23FFB000

Add titlebar colouring

---

src/InteractiveAtom.tsx

Updates the prop types of `AtomInteractive` following a recent update that made some optional props compulsory.

Correct the `InteractiveAtom` type

---

src/ExplainerAtom.stories.tsx
src/ExplainerAtom.tsx

Before all text was inheriting the page style, which overrode any italic styles, especially in the poetry. This should now be fixed
Before:
After:

Italics now work in Explainers and a story has been added

---

.vscode/settings.json
package.json
yarn.lock

- Explicitly set typescript version in `devDependencies` and `peerDependencies`
- VSC fetch typescript version for `node_modules`
Using JSX instead of React throws TS issues for older versions of TS. To avoid these issues we should remove the ambiguity of what TS version is running in the repo

Manage typescript version in package.json

---

package.json
rollup.config.js
src/YoutubeAtom.tsx
src/types.ts
yarn.lock

Moves away from `microbundle` and to using `rollup`
- With the introduction of JSX, it is not clear how to configure using `microbundle`
- `microbundle` commnuity has less activity than `rollup`
- `discussion-rendering` uses `rollup`, this helps us keep things inline

Migrate to rollup

---

package.json
tsconfig.json
yarn.lock

- Update to react 17
- set TS compliation to JSX
- We want to use Emotion 11 which has its own JSX runtime
- TS < 4.1 and React 17 support JSX 
- This simplifies using Emotion 11 and using Emotion's JSX runtime

Update React 17 JSX

---

package.json
tsconfig.json
yarn.lock

- Update source packages ot v3.2
- remove `moduleNameMapper` as its is no longer needed
- `jsxImportSource` set to `@emotion/react`
`jsxImportSource` is used to determin the JSX runtime to be used. In our case as we use `css` as an attribute we need to run the project though Emotion's runtime

Update source v3.2

---

.github/workflows/snyk.yml

Splits the GH Action out to run snyk test and upload SARIF file to code
scanning and then run snyk monitor if on `main`. We can now test dev
dependencies by pruning repeated subdependencies. This was failing prior
to this due to too many vulnerable paths.

Fix snyk gh action

---

README.md
src/Answers.tsx
src/KnowledgeQuiz.stories.tsx
src/KnowledgeQuiz.tsx
src/PersonalityQuiz.stories.tsx
src/PersonalityQuiz.tsx

Updates quiz atom fonts, namely:
- For knowledge quizzes, the (non-revealed) answers are now also using a serif font (they were accidentally using sans, via source's default)
- For both knowledge and personality quizzes, we update the question and answer font choice to be text sans for labs content

Consistent themed fonts for quizzes

---

src/lib/unifyPageContent.tsx

This switches from using `preact-render-to-string` to `react-dom/server` for the `renderToString` function.
We use a mix of React and Preact across the department, and [common](https://github.com/guardian/dotcom-rendering/blob/14779a173d9f19af8dbab456749f1421d5a372fd/scripts/webpack/frontend.js#L29) [practice](https://github.com/guardian/support-frontend/blob/4048812d6f0c572ba1803c0f3b3d7d78fa3823dd/support-frontend/webpack.common.js#L97) in Preact codebases is to treat React as the default and alias to `preact-compat`. Therefore I think it's best to also treat React as the default in our libraries, and let the consumers decide whether they want to alias that to Preact.
This will also mean that we can remove an [awkward workaround](https://github.com/guardian/apps-rendering/blob/94b2640fe9 …

`react-dom` Over `preact-render-to-string`

---

src/InteractiveAtom.tsx
src/lib/unifyPageContent.test.tsx
src/lib/unifyPageContent.tsx

Some legacy interactive atoms do not contain any js in the element object returned from capi. When loading the interactive via dcr this results in a schema error, see https://github.com/guardian/dotcom-rendering/pull/3204. However, to rectify this issue atoms-rendering requires an update to the type interface. This PR relaxes the interactive atom type by making property elementJs type string or undefined.
Along with deployment of associated dcr changes, legacy interactive atoms load successfully, eg https://www.theguardian.com/us-news/ng-interactive/2017/jan/26/obamacare-what-next-healthcare-preexisting-conditions?dcr. 
After deployment, along with https://github.com/guardian/dotcom-rendering/pull/3204, legacy interactive atoms successfully render via dcr.
Risk is low as the change is …

update InteractiveAtomType interface to allow undefined elementJs

---

README.md
src/YoutubeAtom.tsx
src/types.ts

Amend `YoutubeAtom` to accept `adsConfig: { disableAds: true }` as a flag to pass to the YouTube player.
Follows method in Frontend [youtube-player](https://github.com/guardian/frontend/blob/df31b4deeb7f72303ebfa766f6a2699e2be1a293/static/src/javascripts/projects/common/modules/atoms/youtube-player.ts#L171)
1. Log in as a subscribed user
2. Checking a DCR rendered video page such as [this one](https://www.theguardian.com/science/2021/jul/20/jeff-bezos-rocket-design-an-inquiry). It should not show an ad before the video
DCR PR https://github.com/guardian/dotcom-rendering/pull/3225 is dependent on this change.

YoutubeAtom should respect adfree users

---

src/KnowledgeQuiz.tsx

This is a temporary fix while the root problem is found for knowledge type quizzes to display the wrong message. 
For now these messages have been turned off until the solution is found.

Temporary fix for Knowledge quizzes

---

src/KnowledgeQuiz.stories.tsx
src/KnowledgeQuiz.tsx
src/fixtures/knowledgeQuizAtom.ts

This reworks the logic for knowledge quizzes. Previously batched scores had not been accounted for i.e. scoring between 1 and 5. This will account for a response to every question and batched questions.

Reworked Quiz Logic

---

package.json
yarn.lock

Removes Preact as it is no longer used.
This has the happy side effect of fixing yarn linking issues in DCR as explained below.
1. This previous [workaround](https://github.com/guardian/atoms-rendering/pull/143) meant `preact-render-to-string` was introduced to `atoms-rendering`
1. Because `preact-render-to-string` was introduced to `atoms-rendering` any React app that transpiled `atoms-rendering` had to implement a (reverse) webpack alias:
`'preact-render-to-string': 'react-dom/server'`
1. Because `preact` was added to `atoms-rendering` when yarn/npm linking to a consuming app that also had `preact` (e.g. DCR) runtime exceptions would be thrown because of known artifacts with yarn/npm linking.
Given there is a fix for 1. and `preact` has been removed from `atoms-rendering`, we can now …

Remove unused preact. Fixes DCR yarn linking

---

package.json
src/Answers.stories.tsx
src/Answers.tsx
src/AudioAtom.tsx
src/ChartAtom.tsx
src/ExplainerAtom.tsx
src/KnowledgeQuiz.tsx
src/PersonalityQuiz.tsx
src/Picture.tsx
src/SharingIcons.tsx
src/TimelineAtom.tsx
src/YoutubeAtom.tsx
src/expandableAtom/Body.tsx
src/expandableAtom/Container.tsx
src/expandableAtom/Footer.tsx
src/expandableAtom/Summary.tsx
src/lib/pillarPalette.ts
yarn.lock

We have published a Source v4 release candidate, and are keen for dotcom-rendering and apps-rendering to be first benefit from the improved developer ergonomics 🎉   In order to do this, we must update packages that they depend on, so as to avoid bundling both v3 and v4 of Source.
We have written an eslint plugin that has automated the majority of the upgrade. 
Source now comprises 3 packages:
- `@guardian/source-foundations`: equivalent to `@guardian/src-foundations`
- `@guardian/source-react-components`: contains all components from packages that were prefixed `@guardian/src-*`
- `@guardian/source-react-components-development-kitchen`: New and experimental components

Migrate atoms-rendering to source v4

---

package.json
src/InteractiveAtom.stories.tsx
src/InteractiveAtom.tsx
yarn.lock

This extends the work done in [this PR](https://github.com/guardian/atoms-rendering/pull/243 ) by @liywjl to limit that fix to only apply to immersive articles.
The 100% height fix is still needed to prevent the iframe resize from being constrained by its container and ending up choosing a height of 150px - which was the old problem. But on liveblogs the same fix has the opposite effect.
There's an argument at this point that we could review the various containers we are rendering main media in different contexts. Perhaps there's a way to rationalise things to remove the need for this and the original work. I did go down this route, it wasn't as simple as I wanted and I felt that I was starting to introduce more risk and complexity that the situation justified. Instead, by passing in …

fix: Only apply `height: 100%` to interactive main media when `Immersive`

---

src/GuideAtom.tsx
src/ProfileAtom.tsx
src/QandaAtom.tsx
src/TimelineAtom.tsx
src/lib/ophan.ts
src/types.ts

This makes the tracking handlers used by some atoms optional
We allow these handlers to be passed in in case different platforms want to track things differently. This change still allows this but adds a default so the handler is no longer required

Optional tracking handlers

---

src/YoutubeAtom.tsx

Currently `YoutubeAtom` does not fire it's `EventEmitters` i.e. Ophan and GA. 
The root cause of this is that we are loading the YouTube iFrame twice.
This is because the `setIframeSrc` useEffect fires twice:
-  the first time when `loadIframe` becomes true (when `interactionStarted`)
-  the second time is when `hasUserLaunchedPlay` toggles  (when the user clicks play).
The second iFrame load causes the first player instance to be removed, taking the attached player and all the listeners with it.
The temporary fix is to not call `setIframeSrc` a second time.
It is a temporary fix as we plan to refactor this component to simplify the internal state, logic and separate the player from the UI.
We don't load the iFrame twice.
Ophan and GA progress events should fire: `play`, `25`, `50`, `75`, …

Fix `YoutubeAtom` Ophan and GA Events

---

src/YoutubeAtom.tsx

This PR removes an optimisation that existed on the `YouTubeAtom` to download the youtube files early when the mouseover event fired.
The existence of this optimisation is a problem for two reasons:
1. It is complicating state management and causing bugs. In some situations we're seeing videos not being played (especially in conjunction with a [recent PR ](https://github.com/guardian/atoms-rendering/pull/330)to prevent the iframe being loaded twice).
2. We intend to refactor this component and simpler state will be easier to reason about
This means that, in those cases where the optimisation was triggered (desktop, mainly) we're now asking the user to wait longer for the content to play. In most situations the time between `mouseover` and `click` is so small this will make little …

Remove interaction optimisation on `YouTubeAtom`

---

src/YoutubeAtom.tsx

Use the platform! We can get rid of `encodeURIComponent`.
Easier for people to feel confident making changes.
If the string was formatted differently, we might have issues with Youtube atoms. Hopefully these would be caught by existing tests.

refactor: use URLSearchParams to create search params

---

src/YoutubeAtomPlayer.tsx
src/types.ts

As part of the sticky video work we need to have greater awareness of the player state of youtube videos.
This PR adds the following event emitters:
- `resume` if the player has already played once but been paused
- `paused` if the player has been paused
- `cued` if the player has been stopped
Given we don't need to send these events to Ophan or GA i'm unsure as to whether we need to include the `log()` sections?
Go to storybook, open dev tools and play / pause / stop the video.

Add event emitters for `resume`, `pause` and `cued`

---

.github/workflows/changesets.yml
README.md
package.json

Makes changesets the default release method.
Removes unused `NODE_AUTH_TOKEN` value.

Refine changesets workflow

---

.github/workflows/changesets.yml

Reinstate `NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}` as removing it seems to have broken the release process :/

Reinstate NODE_AUTH_TOKEN

---

.changeset/tall-dodos-check.md
src/YoutubeAtom.stories.tsx
src/YoutubeAtomSticky.tsx

Re-orders the contents of the `YoutubeAtomSticky` component so `children` come before the close button. This means that when the button html is conditionally rendered or not, the order of the child components does not change.

Reorder `YoutubeAtomSticky` contents

---

.changeset/smart-apes-shake.md
src/YoutubeAtom.stories.tsx
src/YoutubeAtom.test.tsx
src/YoutubeAtom.tsx
src/YoutubeAtomSticky.tsx

Adds an `isMainMedia` prop to the `YoutubeAtom` which is in turn passed to the `YoutubeAtomSticky` component, allowing us to adjust the sticky videos position for main media videos.
Currently the sticky video aligns with the right hand margin of its original container, if this a main media video we need to add `20px` padding right.
The DCR PR to implement these changes once the new version of Atoms Rendering is released [is here](https://github.com/guardian/dotcom-rendering/pull/4426).
- added `isMainMedia` prop
- tidied up `stickyContainerStyles`
- made `shouldStick` prop optional for consistency in DCR

Add isMainMedia prop to `YoutubeAtom`

---

.changeset/small-jobs-shave.md
src/YoutubeAtomSticky.tsx

Adds a listener to allow users to closes the sticky video on `esc` key press.
Run storybook, go to the `YoutubeAtom/sticky` story, play the video, scroll down to stick and close using the `escape` key.

Close sticky video on esc press

---

src/YoutubeAtom.test.tsx

Corrects an incorrect prop name in the `YoutubeAtom` tests. This sneaked in as part of [this PR](https://github.com/guardian/atoms-rendering/pull/367/files).

Correct "mainMedia" to "isMainMedia" in `YoutubeAtom` tests

---

.changeset/neat-bees-suffer.md
src/Picture.tsx
src/YoutubeAtom.tsx
src/YoutubeAtomOverlay.tsx
src/YoutubeAtomPlayer.tsx

As part of the sticky videos work, and recently highlighted by the DAC reports, we've become aware that YoutubeAtom's were difficult to use with keyboard only navigation.
This PR removes the `tabIndex` values, and makes the overlay component a `button` rather than a `div`. The result is an atom which is much easier to navigate using keyboard controls.
DAC issues:
[Active elements were found that could not be navigated to via the keyboard.](https://drive.google.com/file/d/1S8ElKJj6sRNrEu5zQNp6fGejocXKgUM-/view
)
[Missing focus indicator](https://drive.google.com/file/d/1-aPrCLPJm-7lqiwrSwyfRc1BfP138YIa/view
)
Go to storybook `YoutubeAtom/Overlay`, tab into the component and use `enter` to start the video. The controls should be available by keyboard navigation. …

Fix `YoutubeAtom` tabbing issues

---

.changeset/six-tables-retire.md
src/YoutubeAtom.stories.tsx
src/YoutubeAtom.test.tsx
src/YoutubeAtom.tsx
src/YoutubeAtomOverlay.tsx
src/YoutubeAtomPlayer.tsx

This PR addresses issues raised in the DAC report by adding an `aria-label` to the `YoutubeAtom` overlay `play` button, and a `title` to the iframe.
DAC Issues:
[Ensure all <frame> and <iframe> elements have valid title attribute values.
](https://drive.google.com/file/d/1ZXsQqmImEIx0cirPPRsaX1LKRCeoPZp5/view)
[For each instance of this ‘Play Video’ button, the video that it is in relation should be included within
the button text.](https://drive.google.com/file/d/1hBH7i4qJVeh6Wu_laQ5FLzmL_IZbAjIe/view)

Add title to `YoutubeAtom` button label and iframe

---

.changeset/late-birds-deliver.md
src/YoutubeAtomSticky.tsx

Reduces the height of the sticky video container to match the video height for phablets and above to prevent a content shift when the video sticks, is closed or is reinserted into its container.
https://user-images.githubusercontent.com/20416599/161040586-e31d6a52-bdc4-4552-9dbc-e620e1c44dc5.mov
https://user-images.githubusercontent.com/20416599/161040495-4cd9d52a-cf3b-4061-9380-551b894d97ed.mov

Fix: sticky video content layout jump 

---

.changeset/gorgeous-fans-peel.md
src/YoutubeAtom.stories.tsx
src/YoutubeAtom.test.tsx
src/YoutubeAtom.tsx
src/YoutubeAtomOverlay.tsx
src/YoutubeAtomPlaceholder.tsx
src/YoutubeAtomPlayer.tsx
src/YoutubeAtomSticky.tsx

Fixes a bug when we have duplicate videos on the same page.
This issue is more apparent on liveblogs where the same video can be in the main media position and in a block.
This is the corresponding DCR fix to the Frontend fix: https://github.com/guardian/frontend/pull/24713
Currently we use the `videoId` for the YouTubeAtom component ids e.g. :
`<div id="youtube-player-${videoId} ...>`
This is not unique when there are multiple instances of the same video and hence the YouTube player will not mount duplicate instances.
The fix is to combine `elementId` as provided by `DotcomRenderingDataModel` e.g. :
`<div id="youtube-player-${videoId}-${elementId} ...>`
With this the YouTube player can correctly select and mount each video instance.
Expects `elementId` to be passed from DCR as detailed …

YoutubeAtom - Fix Duplicate Videos

---

.changeset/pink-drinks-give.md
src/YoutubeAtom.stories.tsx
src/YoutubeAtomPlayer.tsx

Paired with @joecowton1 and @arelra 
This PR adds logic to pause the video whenever another video is played in the same page. This way we can't have multiple videos playing simultaneously. 
**Storybook:**  this feature has been tested in storybook and can be checked [here](https://5f22d2148807980022fc782e-aryeqruwej.chromatic.com/?path=/story/youtubeatom--multiple-videos)
**Manual testing in DCR CODE after publishing the package:** This change needs to be deployed and published. We can then test DCR in code using the new version of atoms-rendering by going to this [page](http://localhost:3030/Article?url=https://www.theguardian.com/world/live/2022/mar/28/russia-ukraine-war-latest-news-zelenskiy-putin-live-updates) which has three videos. 
when 1 video is already playing, if you play the …

stop other playing videos when a video plays

---

.changeset/orange-nails-care.md
src/YoutubeAtom.tsx
src/YoutubeAtomPlayer.tsx

@paperboyo reported an issue where clicking along a sticky video's timeline would cause the video to stick and unstick. 
This was caused by the `play` and `resume` video events sticking and unsticking the video via the `isPlaying` state in the `YoutubeAtom`.
To resolve this issue we've removed those events from the `playerState` function, and reverted to using `stop` rather than `pause` when multiple videos are played on the same page. If we'd left this so the previous video was paused when a new video was played, they both would remain sticky rather returning to the original container.
https://user-images.githubusercontent.com/77005274/162753873-cf92bc80-f61e-40f4-8421-a51d783f84df.mov
https://user-images.githubusercontent.com/77005274/162753962-65bec82f-7a08-4772-af7d-c87bd351a96e.mov

Remove pause and resume events from `YoutubeAtom` playerState function

---

.changeset/loud-eels-notice.md
src/YoutubeAtomSticky.tsx

Adds a missing flag to include tablets in the device check: https://github.com/juliangruber/is-mobile

Add missing 'tablet' flag to isMobile config in `YoutubeAtomSticky` 

---

.changeset/beige-snails-agree.md
package.json

Moves `isMobile` dependency to `dependencies` as the DCR check's were failing with it as a dev dependency.

Move isMobile dependency

---

.changeset/wise-badgers-impress.md
src/RecipeSchemaAtom.test.tsx
src/RecipeSchemaAtom.tsx
src/index.ts
src/types.ts

This is an attempt to add a barebones recipe atom which simply renders [schema](https://schema.org/Recipe) out of sight for the benefit of web crawlers/search engines. This is part of a proposed experiment to get structured data on a handful of recipe pages and get a before/after view on search engine performance.
We believe all that's needed is a script tag containing a [JSON-LD](https://json-ld.org/) blob. The example used in the atom test has been run through Google's [Rich Results Test](https://search.google.com/test/rich-results) and seems to work fine. 
My thanks to @shtukas for helping me piece this together!

Recipe schema atom

---

.changeset/new-panthers-retire.md
src/expandableAtom/Footer.tsx

Adds `aria-label` to like and dislike buttons, previously a screen reader would announce these as "button" instead of anything descriptive.
Also makes them easier to click from voice control.
Fixes guardian/dotcom-rendering#5073

fix: Add aria labels to like dislike buttons

---

.changeset/seven-meals-think.md
package.json
src/YouTubePlayer.ts
src/YoutubeAtom.stories.tsx
src/YoutubeAtomPlayer.tsx
src/loadYouTubeIframeApi.ts
yarn.lock

- Removes [`youtube-player`](https://www.npmjs.com/package/youtube-player) from the project dependencies and replaces it with 
- `loadYouTubeIframeApi` function to load the Youtube iframe api script
-  our own `YouTubePlayer` class which acts as a wrapper over the YouTube Iframe API's player object and "promisifies" the player methods so that they're executed only when the player is ready, much like `youtube-player` does.
- Small change to YoutubeAtom MultipleVideos story so that it includes three different videos 
- Removes 11.2kB / 4.2kB gzip from bundled dependencies
- In a subsequent PR we'd like to make a change to `loadYouTubeIframeApi` to enable us to create an experiment to test [interactive media ads](https://developers.google.com/interactive-media-ads) on first-party videos. In …

Remove `youtube-player` library

---

.changeset/fifty-lies-explode.md
README.md

Corrects name of auto generated changesets PR in readme.

Update readme with correct naming for changesets release PR

---

.changeset/mean-ducks-float.md
src/YouTubePlayer.ts
src/YoutubeAtomPlayer.tsx

- Introduces an improvement to the `YoutubeAtomPlayer` component to remove event listeners from the `YT. Player` object before `YoutubeAtomPlayer` unmounts.

YoutubeAtomPlayer removes YouTube event listeners before unmount

---

.changeset/slimy-starfishes-judge.md
src/loadYouTubeIframeApi.ts

- `loadYouTubeAPI` and the [equivalent function in `youtube-player`](https://github.com/gajus/youtube-player/blob/master/src/loadYouTubeIframeApi.js#L9) that we replaced in #434 have a bug which causes a potential race condition. Since the youtube iframe api script is loaded before `window.onYouTubeIframeAPIReady` is defined, there is a possibility that the script will finish loading, the youtube api will be "ready", and the ready function will be called before it's defined. If this happens, the promise returned by `loadYouTubeAPI` never resolves and `YoutubeAtomPlayer` isn't made aware of the fact that the player is ready. For players with an overlay, the placeholder is never removed and the YoutubeAtom component appears as a black rectangle.
- This PR removes the race condition by …

Fix: prevent race condition in `loadYouTubeAPI`

---

.changeset/wise-lemons-rule.md
src/YouTubePlayer.ts
src/YoutubeAtom.stories.tsx
src/YoutubeAtom.tsx
src/YoutubeAtomPlayer.tsx
src/YoutubeAtomSticky.tsx

Co-authored-by: Zeke Hunter-Green <zeke.huntergreen@guardian.co.uk>
- Update YoutubeAtom behaviour to pause rather than stop when:
- another video is played on the same page
(introduced: #401)
- a sticky video is closed
- Rename `isPlaying` to `isActive` to more closely reflect that the video has started but may be paused. This also helps avoid multiple videos sticking - only an active video can be sticky
- Introduce new state hook `isClosed` to stop a closed video from re-sticking
We have done this for a couple of reasons:
- pausing is better aligned to how IMA ads integration (#447) expects the player to behave. Stopping a leads to two state changes, unstarted, and cued which triggers an IMA ad playing.
- better user experience - users won't lose their place in a video when closing it …

YoutubeAtom - Pause video rather than stop

---

.changeset/shaggy-forks-type.md
src/KnowledgeQuiz.tsx
src/PersonalityQuiz.tsx
src/fixtures/knowledgeQuizAtom.ts
src/fixtures/personalityQuizAtom.ts

This PR
- Adds support for passing image alts to quiz questions
- Fixes accessibility issue where the legend was not detected, due to it being wrapped in a `<div>`
Can be tested once live with: https://wave.webaim.org/report#/https://www.theguardian.com/lifeandstyle/2021/sep/09/the-guardian-thursday-quiz-general-knowledge-topical-news-trivia-9-september

Quiz Accessibility - Add image alts, fix legends

---

.changeset/green-cooks-check.md
src/YoutubeAtomPlayer.tsx

Enables the IMA YouTube integration UI setting to show an ad label over IMA ads.

Add IMA ad label

---

.changeset/perfect-bears-worry.md
package.json
yarn.lock

Bump `@guardian/libs@^7.1.0` to align types with DCR.
In DCR prop types have diverged since https://github.com/guardian/dotcom-rendering/pull/5750 and tsc fails when bumping atoms-rendering.

Bump `@guardian/libs@^7.1.0`

---

.changeset/healthy-horses-talk.md
package.json
src/lib/pillarPalette.ts
yarn.lock

Bump `@guardian/libs@^9.0.1` to align format with DCR. 
In DCR we're introducing new `SpecialReportAltTheme` and some stories are failing because of some atoms that do not handle it. See more:
https://github.com/guardian/csnx/pull/132
https://github.com/guardian/dotcom-rendering/pull/6201
https://www.chromatic.com/build?appId=5dfcbf3012392c0020e7140b&number=16243
-   [ ] [Tested with screen reader](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md#screen-reader)
-   [ ] [Navigable with keyboard](https://github.com/guardian/accessibility/blob/main/people-and-technology/02-physical.md#keyboard)
-   [ ] [Colour contrast passed](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md#contrast)
-   [ ] [The change doesn't use …

Bump `@guardian/libs@^9.0.1`

---

.changeset/brown-bags-flash.md
package.json
yarn.lock

Whilst working on another PR I was getting erroneous TypeScript errors for discriminated unions.
Upgrading to `typescript@^4.8.4` fixed the erroneous errors.
However this then started a thread pulling exercise of having to upgrade `ts-loader` and `@storybook` to compatible versions:
```
"@storybook/addon-docs": "^6.5.13",
"@storybook/addon-viewport": "^6.5.13",
"@storybook/addons": "^6.5.13",
"@storybook/react": "^6.5.13",
"ts-loader": "^8.4.0",
```
In addtion to the dependency bumps I had to dedupe `@babel` scope using:
` npx yarn-deduplicate --scopes @babel`
as Storybook has an issue with its various tools using slightly different versions of `@babel/core` as explained here:
https://github.com/storybookjs/storybook/issues/14197#issuecomment-949337652
There are still lots of deprecation …

chore: Upgrade TypeScript & Storybook

---

.changeset/weak-bears-shave.md
src/YoutubeAtom.stories.tsx
src/YoutubeAtomPlayer.tsx
src/YoutubeAtomWithImaAd.stories.tsx

Changes the method of displaying the YouTube IMA ad attribution label following a bugfix from Google.
Previously the ad label would not show when the player has an overlay - which is true for the vast majority of our videos.
The ad label appears for all instance of IMA enabled players.
Before:
After:

fix: YouTube IMA ad label

---

.changeset/tricky-carpets-double.md
package.json
src/YoutubeAtomPlayer.tsx
src/YoutubeAtomWithImaAd.stories.tsx
yarn.lock

Bumps `commercial-core` to bring in [full page targeting](https://github.com/guardian/commercial-core/blob/d9de9eb0c8605516f02ed42a63a330f5fb02f719/src/targeting/build-page-targeting.ts) (via https://github.com/guardian/commercial-core/pull/709) for the YouTube IMA integration.
This will allow ad ops to target YouTube IMA ads using all the regular targeting we use in Google Ad Manager.
When running with DCR the IMA request to GAM should have full page targeting on the `cust_params` parameter.
- open developer tools network panel
- ensure you are in the IMA ab test
- click play on a YouTube video
- inspect requests to https://pubads.g.doubleclick.net/gampad/ads?...
- verify `cust_params` contains page targeting with https://guardian.github.io/commercial-request-parser/

feat: Full targeting for YouTube IMA integration

---

.changeset/big-moose-wash.md
package.json
yarn.lock

Bumps commercial-core to `4.24.0`. 
This improves ad targeting in `YoutubeAtomPlayer` via its call to `buildAdsConfigWithConsent` which was updated in commercial-core in [this PR](https://github.com/guardian/commercial-core/pull/708). This brings targeting in line with regular GAM targeting, which we already use for videos rendered by frontend.
- publish this version of `atoms-rendering` and pull it into `dotcom-rendering`
- deploy `dotcom-rendering` to CODE
- load these two articles: [Article 1](https://m.code.dev-theguardian.com/uk-news/video/2022/oct/27/suella-braverman-deserves-second-chance-nadhim-zahawi-video) (rendered by frontend) & [Article 2](https://m.code.dev-theguardian.com/us-news/2022/nov/16/us-midterms-2022-republicans-win-control-house-representatives-congress-midterm-elec …

feat: Bump `commercial-core` to `4.24.0`

---

.changeset/four-bottles-flow.md
package.json
src/YoutubeAtom.stories.tsx
src/YoutubeAtom.tsx
src/YoutubeAtomPlayer.tsx
src/YoutubeAtomWithImaAd.stories.tsx
yarn.lock

Add `abTestParticipations` (aka client side participations) as a prop to `YoutubeAtom` and `YoutubeAtomPlayer` to pass to targeting for YouTube and YouTube IMA integrations.
This allows us target users in ab tests.

feat: YouTube player is passed client side participations for targeting

---

.changeset/twenty-laws-double.md
src/KnowledgeQuiz.tsx
src/PersonalityQuiz.tsx

Improves the accesibility of our quiz atoms by wrapping the questions in a list using an `ol` and `li` tags.
This helps keyboard and screen-reader users to understand the hierarchy better and move quicker between the questions.
Part of https://github.com/guardian/dotcom-rendering/issues/5065
For full fix, this package needs to be updated in `dotcom-rendering`.

Improve accessibility of Quiz atoms

---

.changeset/chilly-pots-drive.md
package.json

Makes `@guardian/commercial-core` and `@guardian/consent-management-platform` optional peer dependencies as they are required in DCR but not Apps-Rendering.

Make peer deps optional
